-- BaseDatos.sql
-- Crea las dos bases del proyecto y carga la data.
-- Postgres ejecuta este script solo la primera vez que se crea el volumen,
-- al hacer docker compose up --build.
--
--   clientes_db  -> servicio de clientes (persona, cliente)
--   cuentas_db   -> servicio de cuentas  (cliente_ref, cuenta, movimiento)

CREATE DATABASE clientes_db;
CREATE DATABASE cuentas_db;


-- ============================ clientes_db ============================
\connect clientes_db

CREATE TABLE IF NOT EXISTS persona (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(255) NOT NULL,
    genero          VARCHAR(20),
    edad            INTEGER,
    identificacion  VARCHAR(50) NOT NULL UNIQUE,
    direccion       VARCHAR(255),
    telefono        VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS cliente (
    id           BIGINT PRIMARY KEY REFERENCES persona (id),
    cliente_id   VARCHAR(50) NOT NULL UNIQUE,
    contrasena   VARCHAR(255) NOT NULL,
    estado       BOOLEAN NOT NULL
);

INSERT INTO persona (id, nombre, genero, edad, identificacion, direccion, telefono) VALUES
    (1, 'Carlos Ramirez', 'M', 30, '1700000001', 'Av. Principal 123', '0991234567'),
    (2, 'Maria Gonzalez', 'F', 28, '1700000002', 'Calle Central 456', '0987654321'),
    (3, 'Juan Perez',     'M', 35, '1700000003', 'Av. Norte 789',     '0971112222');

INSERT INTO cliente (id, cliente_id, contrasena, estado) VALUES
    (1, 'cramirez',  '1234', true),
    (2, 'mgonzalez', '5678', true),
    (3, 'jperez',    '1245', true);

ALTER TABLE persona ALTER COLUMN id RESTART WITH 4;


-- ============================ cuentas_db ============================
\connect cuentas_db

-- copia local de clientes, en runtime se actualiza con los eventos de rabbitmq
CREATE TABLE IF NOT EXISTS cliente_ref (
    cliente_id      VARCHAR(50) PRIMARY KEY,
    nombre          VARCHAR(255),
    identificacion  VARCHAR(50),
    estado          BOOLEAN
);

CREATE TABLE IF NOT EXISTS cuenta (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_cuenta     VARCHAR(50) NOT NULL UNIQUE,
    tipo_cuenta       VARCHAR(20) NOT NULL,
    saldo_inicial     NUMERIC(19,2) NOT NULL,
    saldo_disponible  NUMERIC(19,2) NOT NULL,
    estado            BOOLEAN NOT NULL,
    cliente_id        VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS movimiento (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha            TIMESTAMP NOT NULL,
    tipo_movimiento  VARCHAR(20) NOT NULL,
    valor            NUMERIC(19,2) NOT NULL,
    saldo            NUMERIC(19,2) NOT NULL,
    cuenta_id        BIGINT NOT NULL REFERENCES cuenta (id)
);

INSERT INTO cliente_ref (cliente_id, nombre, identificacion, estado) VALUES
    ('cramirez',  'Carlos Ramirez', '1700000001', true),
    ('mgonzalez', 'Maria Gonzalez', '1700000002', true),
    ('jperez',    'Juan Perez',     '1700000003', true);

-- el saldo_disponible ya tiene aplicados los movimientos de abajo
INSERT INTO cuenta (id, numero_cuenta, tipo_cuenta, saldo_inicial, saldo_disponible, estado, cliente_id) VALUES
    (1, '478758', 'Ahorros',   2000.00, 1425.00, true, 'cramirez'),
    (2, '225487', 'Corriente',  100.00,  700.00, true, 'mgonzalez'),
    (3, '495878', 'Ahorros',      0.00,  150.00, true, 'jperez'),
    (4, '496825', 'Ahorros',    540.00,    0.00, true, 'mgonzalez'),
    (5, '585545', 'Corriente', 1000.00, 1000.00, true, 'cramirez');

ALTER TABLE cuenta ALTER COLUMN id RESTART WITH 6;

INSERT INTO movimiento (id, fecha, tipo_movimiento, valor, saldo, cuenta_id) VALUES
    (1, '2022-02-09 10:00:00', 'Retiro',   -575.00, 1425.00, 1),
    (2, '2022-02-10 10:00:00', 'Deposito',  600.00,  700.00, 2),
    (3, '2022-02-10 11:00:00', 'Deposito',  150.00,  150.00, 3),
    (4, '2022-02-08 09:00:00', 'Retiro',   -540.00,    0.00, 4);

ALTER TABLE movimiento ALTER COLUMN id RESTART WITH 5;
